services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab10-1
      # app.prop : Db = SDPDB-35
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # volume added here

  backend:
    container_name: lab10-1-backend
    build:
    
      context: ./Festivalapi-SpringBoot
      dockerfile: ../Festivalapi-SpringBoot/backend.Dockerfile
    image: lab10-1-backend
    ports:
      - "2051:2050" # edo okati testing 
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: lab10-1-frontend
    build:
      context: ./festival-api
      dockerfile: ../festival-api/frontend.Dockerfile
    image: lab10-1-frontend
    ports:
      - "3011:80"
    depends_on:
      - backend

# Declare volumes at the bottom
volumes:
  mysql-data: